const { Schema, model } = require("mongoose")

/**
 * Document Schema
 * Represents a single collaborative writing session in the database.
 */
const Document = new Schema({
  /* _id: Custom String identifier. 
     In this app, we use the UUID generated by the frontend 
     (e.g., from the /documents/:id route) as the primary key.
  */
  _id: String,

  /* data: Stores the Quill Delta object.
     Using the 'Object' type allows us to save the complex JSON structure 
     that represents rich text formatting, images, and content.
  */
  data: Object,
})

// Export the model to be used for CRUD operations in the server logic
module.exports = model("Document", Document)